name: playwright-automation

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 2 * * *

jobs:
  build:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Install playwright
        run: npm install @playwright/test

      - name: Run test environment and generate JSON report
        env:
          test_env: test
        run: npx playwright test --project=chrome --reporter=dot,json=playwright-report/report.json tests/slack.spec.js

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Extract failed spec names
        id: extract_failed_specs
        run: echo "::set-output name=failed_specs::$(jq -r '.suites[] | select(.status == "failed") | .tests[].fullName' playwright-report/report.json | paste -s -d, -)"

      - name: Download zipped HTML report
        uses: actions/download-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/

      - name: Notify on failure with failed spec names
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"<!here> Playwright tests have failed in the following spec(s): \n\n```\n'"${{ steps.extract_failed_specs.outputs.failed_specs }}""'\n``` \n\nView details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
            ${{secrets.SLACK_WEBHOOK_URLS}}
