---
name: playwright-automation
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: run test environment
        id: playwright
        env:
          test_env: test
        run: |
          output=$(npx playwright test --project=chrome)
          failed_specs_path=$(echo "$output" | jq -r '.failedSpecsPath')
          echo "::set-output name=failedSpecsPath::$failed_specs_path"
        shell: bash
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Download zipped HTML report
        uses: actions/download-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/
      - name: Notify on failure
        if: failure()
        run: >
          failed_specs=$(cat ${{ needs.playwright.outputs.failedSpecsPath }})

          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"<!here> Playwright tests have failed: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}. Failed specs: $failed_specs"}' \
            ${{secrets.SLACK_WEBHOOK_URLS}}
